[package]
name = "sentiment-oracle-program"
version = "0.1.0"
edition = "2021"
authors = ["Sentiment Oracle Team"]

[features]
no-entrypoint = []

[dependencies]
solana-program = "1.16.0"
borsh = "0.10.3"
thiserror = "1.0.40"
sha2 = "0.10.6"

[lib]
crate-type = ["cdylib", "lib"] 